version: '2'
services:
  nginxbms:
    image: nginx
    restart: always
    ports:
        - "80:8080"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./dist:/usr/share/nginx/bms
  bmsserver:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - ./restfulsrv:/app
    environment:
      - MONGO_URL=mongodb://192.168.1.20:27007,192.168.1.114:27007/bms
      - KAFKA_HOST=192.168.1.20:2181
      - listenport=5012
    network_mode: "host"
    ports:
       - "5012:5012"
    expose:
       - "5012"
  kafkadb:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - ./kafkadb:/app
    environment:
      - MONGO_URL=mongodb://172.17.0.1:27018/bms
      - KAFKA_HOST=172.17.0.1:2181
    network_mode: "host"
