version: '2'
services:
  bmscatlserver:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - ./restfulsrv:/app
    environment:
      - MONGO_URL=mongodb://172.17.0.1:27018/bmscatl
      - KAFKA_HOST=172.17.0.1:2181
      - listenport=5013
    network_mode: "host"
    ports:
       - "5013:5013"
    expose:
       - "5013"
  bmscatlkafkadb:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - ./kafkadb:/app
    environment:
      - MONGO_URL=mongodb://172.17.0.1:27018/bmscatl
      - KAFKA_HOST=172.17.0.1:2181
    network_mode: "host"
