version: '2'
services:
  srvdevicegroupcron:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./srvdevicegroupcron:/app
      - ./dist/log:/log
    environment:
      - DEBUG=srvdevicegroupcron:*
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.2.17:27007,192.168.2.18:27007/bmscatl
      - mongos=true
      - logdir=/log
    network_mode: "host"
