version: '2'
services:
  srvexportcron:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /root/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro
      - ./srvintervalexport:/app
      - ./dist/log:/log
      - ./dist/exportdir:/exportdir
    environment:
      - DEBUG=srvinterval:*
      - DEBUG_COLORS=1
      - MONGO_URL=mongodb://192.168.2.17:27007,192.168.2.18:27007/bmscatl
      - mongos=true
      - logdir=/log
      - exportdir=/exportdir
    network_mode: "host"
